FROM ubuntu:24.04

# user and ssh
ENV LC_ALL="C.UTF-8"

RUN apt update
RUN apt install software-properties-common sudo openssh-server -y
RUN mkdir -p /run/sshd
RUN chmod 755 /run/sshd
RUN ssh-keygen -A
RUN useradd -ms /bin/bash moninmout
RUN echo "moninmout:moninmoutpass" | chpasswd
RUN usermod -aG sudo moninmout
RUN echo "moninmout ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
RUN chown -R moninmout:moninmout /home/moninmout
EXPOSE 22

RUN add-apt-repository -y ppa:ondrej/php
RUN apt update
RUN apt install php8.5 php8.5-fpm php8.5-curl php8.5-mysql mariadb-client -y

RUN apt install curl -y
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin/ --filename=composer

RUN apt install git zip -y

CMD while : ; do sleep 1000; done
